### ISSUE TITLE
Script for reproducing the Benchmark

### ISSUE THREAD

**Issue by michaelfeil** [huggingface/text-embeddings-inference#2]
### Feature request

@OlivierDehaene  First - congrats on the product launch!

You mentioned a benchmark in the top line of the readme. 
- I would be interested if there is a script or similar to reproduce the benchmark. (I saw https://github.com/huggingface/text-embeddings-inference/blob/main/load_tests/load.js, but where are the other numbers coming from ;) )
- What is the numerical precision trade-of running FlagEmbeddings with TEI vs e.g. SentenceTransformers.

### Motivation

I created a similar project - https://github.com/michaelfeil/infinity and would like to reproduce the results, and benchmark other libaries.

**Comment by OlivierDehaene** [comment]
We used [this benchmark](https://github.com/huggingface/optimum-benchmark/tree/main/examples/fast-mteb) for PyTorch and Onxx numbers. 

Be aware that the k6 load testing script is benchmarking the whole solution (tokenization + model forward + data H<->D) while the fast-mteb benchmark only benchmarks the model forward.

Regarding the numerical precision, its always hard to evaluate the true impact on downstream tasks. I would advise users to run their own evals. 
We will also add support for bf16 which can help but don't expect much from it.

**Comment by OlivierDehaene** [comment]
What matters in retrieval is not the precision of the embeddings vector; it is the **ranking** of the distances between the vectors. If you loose some decimals in precision it doesn't always reflect in the ranking.

Also, this issue is not specific to TEI. You will face the same issue for any graph fusing engine. ONNX, Nvidia TensorRT or Inferentia Neuron to quote a few, all make approximations in favour of speed. 

In the case of TEI, it comes from the GELU fusing as cuBLASLt does not use exactly the same GELU approximation as the one that is originally used in Transformers. It could be possible to add an "exact" argument to disable the fusing.

c.f. "Its always hard to evaluate the true impact on downstream tasks. I would advise users to run their own evals." and continue to run them in production!
