### ISSUE TITLE
Adding a cache layer

### ISSUE THREAD

**Issue by onel** [huggingface/text-embeddings-inference#254]
### Feature request

Does it make sense for TEI to add a cache layer for embeddings?

Not sure if TEI supports this already.

If not, I'd be curious if it makes sense to add one.
This raises some other questions: where should that live, how big should it be, etc

### Motivation

Even though some models have large vocabs, I think a cache makes sense where some strings repeat often, like in code models.

### Your contribution

No rust experience, but I can help with anything else

**Comment by OlivierDehaene** [comment]
I'm not sure I understand. What do you want to cache exactly? 
Since all models currently supported use bi-directional attention (non-causal if non preffer), it is not possible to cache activations.

**Comment by srisudarsan** [comment]
Not sure, if this is a related question. Is there support for caching the calculated embeddings for a given query string ?
Say If we generate embeddings for a user query, can we cache it so that the embeddings need not be calculated again and can be returned from the cache if the same user query is used as a input to TEI ?

**Comment by OlivierDehaene** [comment]
TEI does not include a cache but it would be super easy to add redic or memcache in your stack to do something like this.
