### ISSUE TITLE
Getting error : Unsupported storage type LongStorage

### ISSUE THREAD

**Issue by Akanksha321** [huggingface/text-embeddings-inference#37]
### System Info

I ma using T4 GPU, and building the docker image with  -
```
model=sentence-transformers/all-MiniLM-L6-v2
revision=main
volume=$PWD/data # share a volume with the Docker container to avoid downloading weights every run

docker run --gpus all -p 8080:80 -v $volume:/data --pull alwaysghcr.io/huggingface/text-embeddings-inference:turing-0.2.2 --model-id $model --revision $revision
```
Returns embeddings as - 
```
[[null, null, null................................................................................., null]]
```

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

When running the docker for model - sentence-transformers/all-MiniLM-L6-v2, I am getting the error : 
skipping embeddinggs.position_ids: Msg("Unsupported storage type LongStorage")

```
model=sentence-transformers/all-MiniLM-L6-v2
revision=main
volume=$PWD/data # share a volume with the Docker container to avoid downloading weights every run

docker run --gpus all -p 8080:80 -v $volume:/data --pull alwaysghcr.io/huggingface/text-embeddings-inference:turing-0.2.2 --model-id $model --revision $revision
```

### Expected behavior

On running curl request, a list of embeddings  should have been returned. However, now just a list of null values is being returned, on the curl request- 
```
curl 127.0.0.1:8080/embed \
    -X POST \
    -d '{"inputs":"What is Deep Learning?"}' \
    -H 'Content-Type: application/json'
```

**Comment by OlivierDehaene** [comment]
It seems to be the case for all models with `head_size == 32` specifically on T4. 
I will update here once I find the issue.

**Comment by OlivierDehaene** [comment]
Unfortunately it seems to be a precision issue in the flash attn v1 kernel that is used on Turing. Flash attn v2 does not seem to have the same issue. 
#41 adds float32 support for Cuda to avoid the issue but it is not fully optimised yet.

**Comment by OlivierDehaene** [comment]
#41 was merged and should solve your issue with the `latest` image.

**Comment by praveen-krsna** [comment]
I tried to convert RMBG-1.4 model(https://huggingface.co/briaai/RMBG-1.4) but got this error given below.
Can anyone suggest how to fix it ? Mostly the error seems be due to torch package version issue.

PS E:\ai-folder> python llama.cpp/convert.py E:\jan\models\RMBG-1.4 --outfile RMBG-1.4.gguf --outtype f32
Loading model file E:\jan\models\RMBG-1.4\pytorch_model.bin
Traceback (most recent call last):
  File "E:\ai-folder\llama.cpp\convert.py", line 1478, in <module>
    main()
  File "E:\ai-folder\llama.cpp\convert.py", line 1414, in main
    model_plus = load_some_model(args.model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ai-folder\llama.cpp\convert.py", line 1274, in load_some_model
    models_plus.append(lazy_load_file(path))
                       ^^^^^^^^^^^^^^^^^^^^
  File "E:\ai-folder\llama.cpp\convert.py", line 887, in lazy_load_file
    return lazy_load_torch_file(fp, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ai-folder\llama.cpp\convert.py", line 843, in lazy_load_torch_file
    model = unpickler.load()
            ^^^^^^^^^^^^^^^^
  File "E:\ai-folder\llama.cpp\convert.py", line 832, in find_class
    return self.CLASSES[(module, name)]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: ('torch', 'LongStorage')
PS E:\ai-folder>
