### ISSUE TITLE
/embed api return [[null,null,null]...]

### ISSUE THREAD

**Issue by lzy199qwe** [huggingface/text-embeddings-inference#53]
### System Info

docker : ghcr.io/huggingface/text-embeddings-inference:turing-0.2.0 

model: https://huggingface.co/intfloat/multilingual-e5-base

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

1. docker run  -i -t --rm --name embed-model --runtime=nvidia --gpus='"device=1"' -e LOG_LEVEL=debug -p 18081:80 -v /multilingual-e5-base:/embed_model/   --shm-size="16gb" ghcr.io/huggingface/text-embeddings-inference:turing-0.2.0 --model-id /embed_model
2. test with this input :
{
  "inputs": "string",
  "truncate": false
}
and sometimes it get correct anwer, while sometimes get this:
![image](https://github.com/huggingface/text-embeddings-inference/assets/35828422/a824195c-7cb4-4602-accb-a5f21d74bf13)

### Expected behavior

all correct

**Comment by OlivierDehaene** [comment]
Use 0.3.0.

**Comment by lzy199qwe** [comment]
> Use 0.3.0.

should i specify --dtype=float32?
i have tried --dtype=float16 with 0.3.0 in T4， still have this problem..
and i tried --dtype=float32，it seems normal but have very low speed..

**Comment by OlivierDehaene** [comment]
Unfortunately it's a precision issue that we have with flash attention v1 on Turing. It's very annoying because some models work and other don't. This is why Turing support is marked as "experimental" in the README.

I'm adding the `USE_FLASH_ATTENTION` env var in this [PR](https://github.com/huggingface/text-embeddings-inference/pull/57). You will then be able to turn it ON/OFF depending on the model.
