### ISSUE TITLE
--model-id does not work for local dirs

### ISSUE THREAD

**Issue by zhengxu001** [huggingface/text-embeddings-inference#67]
### System Info

CentOS 7

### Information

- [X] Docker
- [ ] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

When I run `docker run --gpus all -p 8080:80 -v $vol:/data --pull always ghcr.io/huggingface/text-embeddings-inference:0.3.0 --model-id $model`

Where `$model=/local/path/of/fine-tuned/model`

It always makes request to huggingface with error:
`request error: HTTP status client error (404 Not Found) for url (https://huggingface.co//local/path/of/fine-tuned/model/resolve/main/1_Pooling/config.json)
`

May I know how to load a local model properly? Thanks!

### Expected behavior

Load the local fine-tuned model instead of downloading model from HuggingFace.

**Comment by ftmtk** [comment]
I had the same issue. `--pooling` arg results in an error about finding a config under `1_Pooling/config.json`. But this file cannot be found.

**Comment by rchanggogogo** [comment]
> ### System Info
> CentOS 7
> 
> ### Information
> * [x]  Docker
> * [ ]  The CLI directly
> 
> ### Tasks
> * [x]  An officially supported command
> * [ ]  My own modifications
> 
> ### Reproduction
> When I run `docker run --gpus all -p 8080:80 -v $vol:/data --pull always ghcr.io/huggingface/text-embeddings-inference:0.3.0 --model-id $model`
> 
> Where `$model=/local/path/of/fine-tuned/model`
> 
> It always makes request to huggingface with error: `request error: HTTP status client error (404 Not Found) for url (https://huggingface.co//local/path/of/fine-tuned/model/resolve/main/1_Pooling/config.json) `
> 
> May I know how to load a local model properly? Thanks!
> 
> ### Expected behavior
> Load the local fine-tuned model instead of downloading model from HuggingFace.

you need to change the docker $volumn as your local model path, and change model_id to /data/model_id.

**Comment by OlivierDehaene** [comment]
You run:
`ocker run --gpus all -p 8080:80 -v $vol:/data --pull always ghcr.io/huggingface/text-embeddings-inference:0.3.0 --model-id $model`
So your volume is in `/data` when running the container.

Since `model=/local/path/of/fine-tuned/model`, the process cannot find the model since `/local` was not shared.

**Comment by OlivierDehaene** [comment]
@ftmtk, can you open another issue?

**Comment by zhengxu001** [comment]
Great thanks @rchanggogogo and @OlivierDehaene , it works following your steps.

**Comment by Ncifra** [comment]
Hi,

I am having the same issue but can't quite understand the paths being used. I am running it like:
`docker run -p 8080:80 -v $volume:/path/to/model/folder --pull always ghcr.io/huggingface/text-embeddings-inference:cpu-0.6 --revision $revision --model-id $model`

and have these variables:
`revision=refs/pr/5`
`volume=$PWD/data`
`model=/folder` (tried `/data/folder` too)

but have the same issue where it seems to be tried from the huggingface online repo instead of the local model.
